### ISSUE TITLE
validate imported files before any further processing

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/teiminator#2]
Documents (CMFI, CMDI, and TEI) should be validated before doing anything else with.

**Comment by csae8092** [comment]
see here for xsds for CMDI

**Comment by dariok** [comment]
For now, I assume that a schema has been included in the XML file, either as PI (`xml-model`) or via `/1/@xsi:schemaLocation` – if we use a static schema, customisations would be ignored

**Comment by csae8092** [comment]
as it turned out, implementing some validation logic either comes with a lot of overhead and/or put (too) much constraints on documents which would like to use TEIminator's services (like `assume that a schema has been included in the XML file`) 
Therefore we (for) now on simply wrap the transformation process in a `try - catch` block and if it works, then fine, and if not, we provide some human readable instructions on how to proceed
