### ISSUE TITLE
check mime-type

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/teiminator#3]
only binaries with mime-type application/xml should be processed

**Comment by dariok** [comment]
Will check that a valid URL has been given and the file is available; check for MIME type should be done by `doc()` (or rather, it should only succeed if the URL given is a well-formed XML and only then return the document node).

**Comment by csae8092** [comment]
closed for similar reasons as pointed out here https://github.com/acdh-oeaw/teiminator/issues/2#issuecomment-320881548
