### ISSUE TITLE
check max file size

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/teiminator#4]
lets say not bigger then 10MB
all checks should happen before any further processing

**Comment by dariok** [comment]
Cannot be done at the moment. As only a URL is given to the script, we cannot check for the file size (this is only possible for multipart transfers from browser to server).

**Comment by csae8092** [comment]
do you think it is possible to set some kind of time out variable which kills any transformation/validation process after XX seconds?

**Comment by dariok** [comment]
That should be possible, yes. What timeout would be okay? 15 seconds?

**Comment by csae8092** [comment]
ok

**Comment by dariok** [comment]
In order for this to work, we need to run the service .xql in a dba role.
Problems may occur if simultaneous requests are made to the same script at the exact same time.

**Comment by dariok** [comment]
Okay, what I tried in the last commit should be working even if not run in a dba role.

**Comment by csae8092** [comment]
to much server load should be prevented by timeout setting now
